Bugfix for enforce module use policy.
spacelift-io/spacelift-policies-example-library pull request #21
Opened 2023-03-08 06:06 UTC by cdhesse

2023-04-01 14:04 UTC, jmfontaine reviewed
Aside from the minor import suggestion and the failing formatting check, it looks good to me. Thanks, @cdhesse!

2023-04-01 14:04 UTC, jmfontaine commented on plan/enforce-module-use-policy.rego
> +import future.keywords
Isn't this enough?

```suggestion
import future.keywords.in
```

2023-04-07 14:21 UTC, jmfontaine requested changes
Thanks for the change.

The last blocker is the failing code formatting check. You can fix that by running `opa fmt -w plan/enforce-module-use-policy.rego` at the root of the repository and committing the changes.

2023-04-12 20:10 UTC, cdhesse commented
> opa fmt -w plan/enforce-module-use-policy.rego

I've tried to get opa to work, but i keep getting errors.

failed to parse Rego source file: 1 error occurred: plan/enforce-module-use-policy.rego:3: rego_parse_error: invalid path future.keywords: path must begin with input or data
        import future.keywords

Even removing the import (which of course I need) - i get other errors.  I can tell you this policy works in our environment (the initial commit does not work however).

2023-04-13 14:34 UTC, jmfontaine approved these changes
@cdhesse Okay, I will merge it as it is, and I will figure it out later. Thanks for your contribution!

2023-04-13 19:47 UTC, merged

2023-04-13 19:48 UTC, jmfontaine commented
Thanks @cdhesse!